export const EDITOR_NAME = 'jk-bms-content-card-editor';
export const MAIN_NAME = 'jk-bms-card';

export enum EntityKey {
    delta_cell_voltage ='delta_cell_voltage',
    balancing_current ='balancing_current',
    power ='power',
    balance_trigger_voltage ='balance_trigger_voltage',
    total_runtime_formatted ='total_runtime_formatted',
    charging ='charging',
    discharging ='discharging',
    balancer ='balancer',
    total_voltage ='total_voltage',
    total_battery_capacity_setting ='total_battery_capacity_setting',
    total_charging_cycle_capacity ='total_charging_cycle_capacity',
    average_cell_voltage ='average_cell_voltage',
    current ='current',
    state_of_charge ='state_of_charge',
    capacity_remaining ='capacity_remaining',
    charging_cycles ='charging_cycles',
    power_tube_temperature ='power_tube_temperature',

    min_voltage_cell ='min_voltage_cell',
    max_voltage_cell ='max_voltage_cell',
    errors ='errors',

    cell_voltage_1 ='cell_voltage_1',
    cell_voltage_2 ='cell_voltage_2',
    cell_voltage_3 ='cell_voltage_3',
    cell_voltage_4 ='cell_voltage_4',
    cell_voltage_5 ='cell_voltage_5',
    cell_voltage_6 ='cell_voltage_6',
    cell_voltage_7 ='cell_voltage_7',
    cell_voltage_8 ='cell_voltage_8',
    cell_voltage_9 ='cell_voltage_9',
    cell_voltage_10 ='cell_voltage_10',
    cell_voltage_11 ='cell_voltage_11',
    cell_voltage_12 ='cell_voltage_12',
    cell_voltage_13 ='cell_voltage_13',
    cell_voltage_14 ='cell_voltage_14',
    cell_voltage_15 ='cell_voltage_15',
    cell_voltage_16 ='cell_voltage_16',

    cell_resistance_1 = 'cell_resistance_1',
    cell_resistance_2 = 'cell_resistance_2',
    cell_resistance_3 = 'cell_resistance_3',
    cell_resistance_4 = 'cell_resistance_4',
    cell_resistance_5 = 'cell_resistance_5',
    cell_resistance_6 = 'cell_resistance_6',
    cell_resistance_7 = 'cell_resistance_7',
    cell_resistance_8 = 'cell_resistance_8',
    cell_resistance_9 = 'cell_resistance_9',
    cell_resistance_10 ='cell_resistance_10',
    cell_resistance_11 ='cell_resistance_11',
    cell_resistance_12 ='cell_resistance_12',
    cell_resistance_13 ='cell_resistance_13',
    cell_resistance_14 ='cell_resistance_14',
    cell_resistance_15 ='cell_resistance_15',
    cell_resistance_16 ='cell_resistance_16',
}